language: node_js
node_js:
- "‘10’"
- 10.15.0

cache:
  directories:
  - "$HOME/.npm"

install:
- npm ci

script:
- CI=false npm run build

deploy:
  provider: firebase
  token:
    secure: BxD7IQ/CtDun4gY9IIL//0gTmerT3yxrTSRRw5TkXBL6uRVgo67zWcJVNaAdsCr0eNjtccSeaSDr04/0XemH45PsYcB76TTiw0KsBXOZ4TuM5eaxHoxkRqxA7+xhEquutISBshFQm1TaWGiVtVAFfNEO77X6Bsuk4MxHedJDBMl4PRf7q+yWbIolEJjb3lC3ZE/BcXOkNRn502ZArqIOr6UBpRi7RYfGw75xQDCyraEoLnUXZxPhpBSIg6cQjzBpC4/FKl4oU2UaAUbbYUqkxT0VEyATQaaLM/Vgg1luqnuO+wv6JGlhMChFdHcRok57JmRku6lYg5rL4z0Nq4rxak7G1iiDeIy5rt/4aLfiqEyuj8Hoqy6vuV0XV3CVeB+fK2fuE/J2p6j3ytitOxRTsNvAUER9X+T/UmwVqMrXWuBtH3SX1i0R9na2ovq/Xc03PvP5MbiWg1kn/zv4sTUkZlEFHAuwm1hWoRcIg98CVd7yk5MLhQBy0nRT1YFnwIfJ3ZuPW3xsavlQsvVNRextFlbAwuR0wvhuhaC5Ftmlpm5EsD7+0gpLv6ageRDgSvCt5/o5tET5Y1hlaso7tzD4Ds7gnRSNjy/+zoCWJ00iJqhfG5vWMsygfH2nlSFzlRNbishUaxeUWPRr8srSkRcUzb/vNu7Tv33Qda32AOC0Af8=
