language: node_js
node_js:
- '10'

cache:
  directories:
    - $HOME/.npm

install:
  - npm ci

script:
  - CI=false npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token: 1/FzB7eoG3yxkjn6meK0jhBy22RXQmxGKst6oQx186z84
